Resources:
  CloudWatchSyntheticsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Description: CloudWatch Synthetics lambda execution role for running canaries
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/CloudWatchSyntheticsFullAccess
      RoleName: CloudWatchSyntheticsRole-commercial_cmp_ca-ca-central-1
  SyntheticsCanary:
    Type: AWS::Synthetics::Canary
    Properties:
      ArtifactS3Location: s3://cw-syn-results-642631414762-ca-central-1/canary/ca-central-1/commercial_cmp_ca-1e1-618bc0f1ef73
      Code:
        Handler: pageLoadBlueprint.handler
        S3Bucket: aws-commercial-canaries
        S3Key: nodejs.zip
      ExecutionRoleArn: arn:aws:iam::642631414762:role/service-role/CloudWatchSyntheticsRole-commercial_cmp_ca-1e1-618bc0f1ef73
      Name: commercial_cmp_ca
      RunConfig: 
        TimeoutInSeconds: 120
      RuntimeVersion: syn-nodejs-puppeteer-3.5
      Schedule: 
        Expression: rate(2 minutes)
      StartCanaryAfterCreation: true
      Tags:
        - Key: blueprint
          Value: heartbeat
  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
          - arn:aws:sns:ca-central-1:642631414762:Commercial_CMP_CA_CloudWatch_Alarms_Topic
      AlarmDescription: Either a Front or an Article CMP has failed
      AlarmName: CA CMP Failed
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
          - Name: CanaryName
            Value: commercial_cmp_ca
      EvaluationPeriods: 3
      InsufficientDataActions: []
      MetricName: SuccessPercent
      Namespace: CloudWatchSynthetics
      OKActions:
          - arn:aws:sns:ca-central-1:642631414762:Commercial_CMP_CA_CloudWatch_Alarms_Topic
      Period: 120
      Statistic: Average
      Threshold: 80
      TreatMissingData: missing


  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: CA CMP Failed
    AlarmDescription: Either on a Front or an Article CMP has failed
    ActionsEnabled: true
    OKActions:
        - arn:aws:sns:ca-central-1:642631414762:Commercial_CMP_CA_CloudWatch_Alarms_Topic
    AlarmActions:
        - arn:aws:sns:ca-central-1:642631414762:Commercial_CMP_CA_CloudWatch_Alarms_Topic
    InsufficientDataActions: []
    MetricName: SuccessPercent
    Namespace: CloudWatchSynthetics
    Statistic: Average
    Dimensions:
        - Name: CanaryName
          Value: commercial_cmp_ca
    Period: 120
    EvaluationPeriods: 3
    DatapointsToAlarm: 3
    Threshold: 80
    ComparisonOperator: LessThanOrEqualToThreshold
    TreatMissingData: missing


