Resources:
  SyntheticsCanary:
    Type: AWS::Synthetics::Canary
    Properties:
      ArtifactS3Location: s3://cw-syn-results-642631414762-ap-southeast-2/canary/commercial_cmp_aus-ac4-26bcc72af596
      Code:
        Handler: pageLoadBlueprint.handler
        S3Bucket: aws-commercial-canaries
        S3Key: nodejs.zip
      ExecutionRoleArn: arn:aws:iam::642631414762:role/service-role/CloudWatchSyntheticsRole-commercial_cmp_aus-ac4-26bcc72af596
      Name: commercial_cmp_aus
      RunConfig: 
        TimeoutInSeconds: 120
      RuntimeVersion: syn-nodejs-puppeteer-3.5
      Schedule: 
        Expression: rate(2 minutes)
      StartCanaryAfterCreation: true
      Tags:
        - Key: blueprint
          Value: heartbeat
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
          - arn:aws:sns:ap-southeast-2:642631414762:AUSCommercialCanaries
      AlarmDescription: Either a Front or an Article CMP has failed
      AlarmName: AUS CMP Failed
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
          - Name: CanaryName
            Value: commercial_cmp_aus
      EvaluationPeriods: 3
      InsufficientDataActions: []
      MetricName: SuccessPercent
      Namespace: CloudWatchSynthetics
      OKActions:
          - arn:aws:sns:ap-southeast-2:642631414762:AUSCommercialCanaries
      Period: 120
      Statistic: Average
      Threshold: 80
      TreatMissingData: missing