Parameters:
  CanaryName:
    Type: String
    MaxLength: 21
    Default: comm_cmp_uk_test
    AllowedValues:
      - comm_cmp_uk_test
      - commercial_cmp_uk
  Environment:
    Type: String
    Default: CODE
    AllowedValues:
      - CODE
      - PROD
  S3Bucket:
    Type: String
    Default: cw-syn-canary-642631414762-eu-west-1
Conditions:
  IsProd: !Equals 
    - !Ref Environment
    - PROD
Resources:
  CloudWatchSyntheticsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Description: CloudWatch Synthetics lambda execution role for running canaries
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/CloudWatchSyntheticsFullAccess
      RoleName: !Sub CloudWatchSyntheticsRole-${CanaryName}-${AWS::Region}
  RolePermissions:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - Ref: CloudWatchSyntheticsRole
      PolicyName: !Sub CloudWatchSyntheticsPolicy-${CanaryName}-${AWS::Region}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetBucketLocation
            Resource:
            - !Sub arn:aws:s3:::${S3Bucket}/*
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:CreateLogGroup
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/cwsyn-${CanaryName}-*
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - xray:PutTraceSegments
            Resource:
              - "*"
          - Effect: Allow
            Action: cloudwatch:PutMetricData
            Resource: "*"
            Condition:
              StringEquals:
                cloudwatch:namespace: CloudWatchSynthetics
  SyntheticsCanary:
    Type: AWS::Synthetics::Canary
    Properties:
      ArtifactS3Location: !Sub s3://${S3Bucket}/canary/${AWS::Region}/${CanaryName}
      Code:
        Handler: pageLoadBlueprint.handler
        S3Bucket: !Sub ${S3Bucket}
        S3Key: !Sub ${Environment}/nodejs.zip
      ExecutionRoleArn:
        Fn::GetAtt:
          - CloudWatchSyntheticsRole
          - Arn
      Name: !Sub ${CanaryName}
      RunConfig: 
        TimeoutInSeconds: 120
      RuntimeVersion: syn-nodejs-puppeteer-3.5
      Schedule: 
        Expression: rate(2 minutes)
      StartCanaryAfterCreation: true
      Tags:
        - Key: blueprint
          Value: heartbeat
  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      ActionsEnabled: true
      AlarmActions:
          - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:CommercialCanaries
      AlarmDescription: Either a Front or an Article CMP has failed
      AlarmName: UK CMP Failed
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 5
      Dimensions:
          - Name: CanaryName
            Value: !Sub ${CanaryName}
      EvaluationPeriods: 5
      MetricName: SuccessPercent
      Namespace: CloudWatchSynthetics
      OKActions:
          - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:CommercialCanaries
      Period: 120
      Statistic: Average
      Threshold: 80
      TreatMissingData: missing