name: AWS Commercial Canary
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14' # chosen arbitrarily
      - name: Run script to create zip files
        run: |
          chmod +x ./.github/scripts/create-artifacts.sh
          ./.github/scripts/create-artifacts.sh
        shell: bash

  upload-files:
    runs-on: ubuntu-latest
    needs: [create-zip-files]

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - uses: guardian/actions-riff-raff@main
        with:
          app: aws-canaries
          stack: commercial
          deployments: |
            upload:
              type: aws-s3
              sources: builds/tcfv2/nodejs.zip
              regions:
                - ca-central-1
              parameters:
                bucket: cw-syn-canary-642631414762-ca-central-1
                cacheControl: private
                publicReadAcl: false
                
  # update-cloudformation:
  #   runs-on: ubuntu-latest
  #   needs: [upload-files]
  #   # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-region: ca-central-1
  #         role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
  #       # # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
  #       # permissions:
  #       #   # required by aws-actions/configure-aws-credentials
  #       #   id-token: write
  #       #   contents: read
  #       uses: guardian/actions-riff-raff@main
  #       with:
  #         app: foo
  #         stack: deploy
  #         deployments: |
  #           builds:
  #             type: cloud-formation
  #             parameters:
  #               templatePath: cmp_tcfv2.yaml
