name: AWS Commercial Canaries

on:
  workflow_dispatch:
  push:

# See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  # required by guardian/actions-riff-raff
  id-token: write
  pull-requests: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Corepack
        run: corepack enable

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: CDK Build
        run: pnpm build

      - name: CDK Synth
        run: pnpm synth

      - name: Run script to create zip files
        run: .github/scripts/create-artifacts.sh
        shell: bash

      - uses: guardian/actions-riff-raff@ab360a150e2540439f7f675c37d170a2fd6c8604 # v4.3.4
        with:
          projectName: frontend::commercial-canaries
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: cdk.out/riff-raff.yaml
          contentDirectories: |
            upload-eu:
              - builds/tcfv2
            upload-ca:
              - builds/tcfv2
            upload-us:
              - builds/ccpa
            upload-aus:
              - builds/aus
            cdk.out:
              - cdk.out
