name: AWS Commercial Canaries

on:
  workflow_dispatch:
  push:

# See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  # required by guardian/actions-riff-raff
  id-token: write
  pull-requests: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Run script to create zip files
        run: .github/scripts/create-artifacts.sh
        shell: bash

      - name: Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: CDK Build
        run: pnpm build

      - name: CDK Synth
        run: pnpm synth

      - uses: guardian/actions-riff-raff@v4.1.8
        with:
          projectName: frontend::commercial-canaries
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: cdk.out/riff-raff.yaml
          contentDirectories: |
            upload-eu:
              - builds/tcfv2
            upload-ca:
              - builds/tcfv2
            upload-us:
              - builds/ccpa
            upload-aus:
              - builds/aus
            cdk.out:
              - cdk.out
