name: AWS Commercial Canaries

on:
  workflow_dispatch:
  push:

# See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  # required by guardian/actions-riff-raff
  id-token: write
  pull-requests: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get Lambda code SHA
        id: getLambdaCodeSha
        run: |
          echo "::set-output name=SHA_ID::$(
            sha1sum ./src/* | sha1sum
          )"
        shell: bash

      - name: Run script to create zip files
        run: |
          chmod +x ./.github/scripts/create-artifacts.sh
          ./.github/scripts/create-artifacts.sh
        shell: bash

      - name: Install CDK dependencies
        working-directory: './cdk'
        run: yarn

      - name: CDK Test
        working-directory: './cdk'
        run: yarn test

      - name: CDK Lint
        working-directory: './cdk'
        run: yarn lint

      - name: CDK Build
        working-directory: './cdk'
        run: yarn build

      - name: CDK Synth
        working-directory: './cdk'
        run: yarn synth

      - uses: guardian/actions-riff-raff@v4
        with:
          app: commercial-canaries
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          config: |
            stacks:
             - frontend
            regions:
              - eu-west-1
              - ca-central-1
              - us-west-1
              - ap-southeast-2
            allowedStages:
              - CODE
              - PROD
            deployments:
              upload-uk:
                type: aws-s3
                regions:
                  - eu-west-1
                parameters:
                  bucket: cw-syn-canary-${{ secrets.AWS_FRONTEND_ACC }}-eu-west-1
                  cacheControl: private
                  publicReadAcl: false
                  prefixStack: false
                  prefixPackage: false
              upload-ca:
                type: aws-s3
                regions:
                  - ca-central-1
                parameters:
                  bucket: cw-syn-canary-${{ secrets.AWS_FRONTEND_ACC }}-ca-central-1
                  cacheControl: private
                  publicReadAcl: false
                  prefixStack: false
                  prefixPackage: false
              upload-us:
                type: aws-s3
                regions:
                  - us-west-1
                parameters:
                  bucket: cw-syn-canary-${{ secrets.AWS_FRONTEND_ACC }}-us-west-1
                  cacheControl: private
                  publicReadAcl: false
                  prefixStack: false
                  prefixPackage: false
              upload-aus:
                type: aws-s3
                regions:
                  - ap-southeast-2
                parameters:
                  bucket: cw-syn-canary-${{ secrets.AWS_FRONTEND_ACC }}-ap-southeast-2
                  cacheControl: private
                  publicReadAcl: false
                  prefixStack: false
                  prefixPackage: false
              commercial-canary-uk:
                type: cloud-formation
                regions:
                  - eu-west-1
                parameters:
                  templateParameters:
                    lambdaCodeSha: ${{ steps.getLambdaCodeSha.outputs.SHA_ID }}
                  templateStagePaths:
                    CODE: CommercialCanaries-UK-CODE.template.json
                    PROD: CommercialCanaries-UK-PROD.template.json
                  cloudFormationStackByTags: false
                  prependStackToCloudFormationStackName: false
                  cloudFormationStackName: commercial-canary
              commercial-canary-ca:
                type: cloud-formation
                regions:
                  - ca-central-1
                parameters:
                  templateParameters:
                    lambdaCodeSha: ${{ steps.getLambdaCodeSha.outputs.SHA_ID }}
                  templateStagePaths:
                    CODE: CommercialCanaries-CA-CODE.template.json
                    PROD: CommercialCanaries-CA-PROD.template.json
                  cloudFormationStackByTags: false
                  prependStackToCloudFormationStackName: false
                  cloudFormationStackName: commercial-canary
              commercial-canary-us:
                type: cloud-formation
                regions:
                  - us-west-1
                parameters:
                  templateParameters:
                    lambdaCodeSha: ${{ steps.getLambdaCodeSha.outputs.SHA_ID }}
                  templateStagePaths:
                    CODE: CommercialCanaries-US-CODE.template.json
                    PROD: CommercialCanaries-US-PROD.template.json
                  cloudFormationStackByTags: false
                  prependStackToCloudFormationStackName: false
                  cloudFormationStackName: commercial-canary
              commercial-canary-aus:
                type: cloud-formation
                regions:
                  - ap-southeast-2
                parameters:
                  templateParameters:
                    lambdaCodeSha: ${{ steps.getLambdaCodeSha.outputs.SHA_ID }}
                  templateStagePaths:
                    CODE: CommercialCanaries-AUS-CODE.template.json
                    PROD: CommercialCanaries-AUS-PROD.template.json
                  cloudFormationStackByTags: false
                  prependStackToCloudFormationStackName: false
                  cloudFormationStackName: commercial-canary
          contentDirectories: |
            upload-uk:
              - builds/tcfv2
            upload-ca:
              - builds/tcfv2
            upload-us:
              - builds/ccpa
            upload-aus:
              - builds/aus
            commercial-canary-uk:
              - cdk/cdk.out
            commercial-canary-ca:
              - cdk/cdk.out
            commercial-canary-us:
              - cdk/cdk.out
            commercial-canary-aus:
              - cdk/cdk.out
