name: AWS Commercial Canary
on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  upload:
    runs-on: ubuntu-latest
    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14' # chosen arbitrarily
      - name: Run script to create zip files
        run: |
          chmod +x ./.github/scripts/create-artifacts.sh
          ./.github/scripts/create-artifacts.sh
        shell: bash
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - uses: guardian/actions-riff-raff@v0.1.0
        with:
          app: commercial-canaries
          stack: frontend
          deployments: |
            upload-ca:
              type: aws-s3
              sources: builds/tcfv2/nodejs.zip
              regions:
                - ca-central-1
              parameters:
                bucket: cw-syn-canary-642631414762-ca-central-1
                cacheControl: private
                publicReadAcl: false
                prefixStack: false
                prefixPackage: false
            commercial-canary-ca:
              type: cloud-formation
              sources: cloudformation/cmp_ca.yaml
              regions:
                - ca-central-1
              parameters:
                templatePath: cmp_ca.yaml
                templateStageParameters: {
                    "CODE": { 
                      "CanaryName": "comm_cmp_ca_test",
                      "Environment": "CODE", 
                      "S3Bucket": "cw-syn-canary-642631414762-ca-central-1", 
                    },
                    "PROD":  { 
                      "CanaryName": "commercial_cmp_ca",
                      "Environment": "PROD", 
                      "S3Bucket": "cw-syn-canary-642631414762-ca-central-1", 
                    },
                }

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - uses: guardian/actions-riff-raff@v0.1.0
        with:
          app: commercial-canaries
          stack: frontend
          deployments: |
            upload-uk:
              type: aws-s3
              sources: builds/tcfv2/nodejs.zip
              regions:
                - eu-west-1
              parameters:
                bucket: cw-syn-canary-642631414762-eu-west-1
                cacheControl: private
                publicReadAcl: false
                prefixStack: false
                prefixPackage: false
            commercial-canary-uk:
              type: cloud-formation
              sources: cloudformation/cmp_uk.yaml
              regions:
                - eu-west-1
              parameters:
                templatePath: cmp_uk.yaml
                templateStageParameters: {
                    "CODE": { 
                      "CanaryName": "comm_cmp_uk_test",
                      "Environment": "CODE", 
                      "S3Bucket": "cw-syn-canary-642631414762-eu-west-1", 
                    },
                    "PROD":  { 
                      "CanaryName": "commercial_cmp_uk",
                      "Environment": "PROD", 
                      "S3Bucket": "cw-syn-canary-642631414762-eu-west-1", 
                    },
                }

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - uses: guardian/actions-riff-raff@v0.1.0
        with:
          app: commercial-canaries
          stack: frontend
          deployments: |
            upload-us:
              type: aws-s3
              sources: builds/ccpa/nodejs.zip
              regions:
                - us-west-1
              parameters:
                bucket: cw-syn-canary-642631414762-us-west-1
                cacheControl: private
                publicReadAcl: false
                prefixStack: false
                prefixPackage: false
            commercial-canary-us:
              type: cloud-formation
              sources: cloudformation/cmp_us.yaml
              regions:
                - us-west-1
              parameters:
                templatePath: cmp_us.yaml
                templateStageParameters: {
                    "CODE": { 
                      "CanaryName": "comm_cmp_us_test",
                      "Environment": "CODE", 
                      "S3Bucket": "cw-syn-canary-642631414762-us-west-1", 
                    },
                    "PROD":  { 
                      "CanaryName": "commercial_cmp_us",
                      "Environment": "PROD", 
                      "S3Bucket": "cw-syn-canary-642631414762-us-west-1", 
                    },
                }

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - uses: guardian/actions-riff-raff@v0.1.0
        with:
          app: commercial-canaries
          stack: frontend
          deployments: |
            upload-aus:
              type: aws-s3
              sources: builds/aus/nodejs.zip
              regions:
                - ap-southeast-2
              parameters:
                bucket: cw-syn-canary-642631414762-ap-southeast-2
                cacheControl: private
                publicReadAcl: false
                prefixStack: false
                prefixPackage: false
            commercial-canary-aus:
              type: cloud-formation
              sources: cloudformation/cmp_aus.yaml
              regions:
                - ap-southeast-2
              parameters:
                templatePath: cmp_aus.yaml
                templateStageParameters: {
                    "CODE": { 
                      "CanaryName": "comm_cmp_aus_test",
                      "Environment": "CODE", 
                      "S3Bucket": "cw-syn-canary-642631414762-ap-southeast-2", 
                    },
                    "PROD":  { 
                      "CanaryName": "commercial_cmp_aus",
                      "Environment": "PROD", 
                      "S3Bucket": "cw-syn-canary-642631414762-ap-southeast-2", 
                    },
                }