name: AWS Commercial Canaries

on:
  workflow_dispatch:
  push:

# See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  # required by guardian/actions-riff-raff
  id-token: write
  pull-requests: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run script to create zip files
        run: |
          chmod +x ./.github/scripts/create-artifacts.sh
          ./.github/scripts/create-artifacts.sh
        shell: bash

      - name: Install CDK dependencies
        working-directory: './cdk'
        run: yarn

      - name: CDK Test
        working-directory: './cdk'
        run: yarn test

      - name: CDK Lint
        working-directory: './cdk'
        run: yarn lint

      - name: CDK Build
        working-directory: './cdk'
        run: yarn build

      - name: CDK Synth
        working-directory: './cdk'
        run: yarn synth

      - uses: guardian/actions-riff-raff@v4
        with:
          app: commercial-canaries
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: cdk/cdk.out/riff-raff.yaml
